### ISSUE TITLE
MUSIC AND SERVER LOGO

### ISSUE THREAD

**Issue by a3rgames** [project-error/pe-basicloading#2]
I wanted to ask if you can put a script for the music and add a logo for the Loading Screen

this script is a  top loading screen but if you put music and a logo it becomes even more beautiful

_thank you_

**Comment by TasoOneAsia** [comment]
Server icon was added with #4 and music is in progress with #3

**Comment by a3rgames** [comment]
Thanks bro i am waiting 

thank you again

**Comment by TasoOneAsia** [comment]
Added with [v1.2.0](https://github.com/project-error/pe-basicloading/releases/tag/v1.2.0)
