### ISSUE TITLE
Loading Screen stuck on artifact 4299

### ISSUE THREAD

**Issue by odessadraekavik** [project-error/pe-basicloading#5]
Using artifact 4299, the loadingscreen is stuck and won't "shutdown".
No errors are shown on the client console or the server console, if I disable the pe-loadingscreen resource i can load in the server fine.

Client build : b2372 (Canary)
Server artifact : 4299 (Windows)
Server build : 2372 (tuner DLC, i've tried with build 2189 and it happens too)

**Comment by RockySouthpaw** [comment]
Are you using any framework? 

You can try removing loadscreen_manual_shutdown 'yes' from the fxmanifest

**Comment by TasoOneAsia** [comment]
I am going to assume you aren't using spawnmanager then, as we listen for the `playerSpawned` event fired from that before shutting down normally.

**Comment by odessadraekavik** [comment]
I finally fixed the problem by commenting this line in fxmanifest.lua
> --loadscreen_manual_shutdown 'yes'
