### ISSUE TITLE
Uncaught Type Error

### ISSUE THREAD

**Issue by tfkmrchu** [project-error/pe-basicloading#7]
Uncaught TypeError: marked is not a function (@pe-basicloading/web/assets/markdown_parser.js:31)

As such, none of the backgrounds are switching, no tips are loading and the logo isn't popping up

**Comment by RockySouthpaw** [comment]
Did you change anytthing?

**Comment by tfkmrchu** [comment]
Only thing that was changed was updating the logo over to our servers logo and added a few backgrounds

**Comment by RockySouthpaw** [comment]
> Only thing that was changed was updating the logo over to our servers logo and added a few backgrounds

Can you show code changes

**Comment by tfkmrchu** [comment]
Sorry, got incredibly busy and didn't do any sort of development work. I've tried reinstalling with no modifications and i keep getting the same error in client console when joining the server. Running fivem version 4901

**Comment by tfkmrchu** [comment]
i've downloaded the source rather than the release version in github (1.4.0), this has fixed it lol
